### ISSUE TITLE
Search results on Search for Terms tab

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#203] opened 2021-08-11 21:33 UTC
Searching for "model" returns appropriate hits for Atomic Terms and Constrained List Options at the top, but then seems to include all Composite Terms that have nothing related to "model" like "Energy Management And Information Systems Boolean", which does not contain "model" in its term name nor in its definition. In fact, I don't think the Search for Terms search list should include any Composite Terms.

**Comment by wizonesolutions** [comment] 2021-08-12 11:01
I think this might be a dupe of the search ticket we did recently. Have you
tested this on staging? https://bedes-mapping-manager-staging.herokuapp.com

Let me know if the search ranking fixes there help.

**Comment by TravisWalterLBNL** [comment] 2021-08-12 15:58
@robHitchcock The first part of this (appropriate results) seems to be fixed on staging (see issue #190). Do you agree?

@wizonesolutions The second part of this is still valid. Under the "Search for Terms" menu, the results should only include BEDES dictionary atomic terms and constrained list options. Composite terms should not be shown here.

**Comment by wizonesolutions** [comment] 2022-02-16 18:09
This one's deploying to staging as well. Check in around 20 minutes. Pay special attention to that composite terms still appear other places you expect them to, just not on Search for Terms.

Could you also comment whether you're still seeing the exact same behavior in #204? I'm just wondering if the various changes we've made to search since have improved it at all.

**Comment by TravisWalterLBNL** [comment] 2022-02-21 22:27
Looks good on staging. Will close after testing on production.

**Comment by wizonesolutions** [comment] 2022-02-23 16:43
Deployed to production.

**Comment by TravisWalterLBNL** [comment] 2022-02-23 20:20
Fixed on production.

**Closed by TravisWalterLBNL** 2022-02-23 20:20 UTC
Labels: bug, high priority
