### ISSUE TITLE
Search results on Applications - New Term - Map to existing Term

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#204] opened 2021-08-11 21:40 UTC
Searching for "model" returns appropriate hits for Atomic Terms and Constrained List Options at the top, but then seems to include Composite Terms that have nothing related to "model" like "Energy Management And Information Systems Boolean" either in their term name or in their definition. This search results list should include Composite Terms, but only those related to the search key word(s).

**Comment by wizonesolutions** [comment] 2021-08-12 11:02
See comment on #203, although I suspect this issue might still exist in staging. Worth double-checking though; let me know.

**Comment by TravisWalterLBNL** [comment] 2021-08-12 15:58
@robHitchcock This seems to be fixed on staging (see issue #190). Do you agree?

@wizonesolutions However, the search results for "Map To Existing BEDES Term" should only contain BEDES atomic terms and composite terms. Constrained list options should not be included in these search results (because application terms cannot be mapped directly to list options).

**Comment by robHitchcock** [comment] 2021-08-12 17:14
@TravisWalterLBNL Not sure I know which site is the staging one at this point. The issue is not fixed on https://bedes-mapping-manager.herokuapp.com/search

**Comment by TravisWalterLBNL** [comment] 2021-08-12 17:46
Staging is here: https://bedes-mapping-manager-staging.herokuapp.com/

**Comment by robHitchcock** [comment] 2021-08-12 17:58
The Search For Terms results (e.g., for "model") on Staging still includes Composite Terms.

**Comment by TravisWalterLBNL** [comment] 2021-08-12 18:07
Yes, but this issue is about the "Map To Existing Term" search results. The "Search For Terms" results are addressed in issue #203.

**Comment by robHitchcock** [comment] 2021-08-12 18:22
Sorry, I got confused.

The "Map To Existing Term" search results on Staging still include many, many Composite Terms that do not include the search key word. The example I keep using for testing is "model" which returns Composite Terms like "Actual Annual Cooling Degree Days Weather Metric Value" that has no "model" word in it, nor I believe do the definitions of the atomic terms used in the composite term.

**Comment by TravisWalterLBNL** [comment] 2021-08-12 18:54
This is strange. When I search for "model" under "Map To Existing Term" on staging, I see 17 results: 2 atomic terms, 4 constrained list options, and the rest are composite terms (all owned by me). All of the composite terms contain either "Model" or "Remodel" in their name. I don't see "Actual Annual Cooling Degree Days Weather Metric Value", even though that term is owned by me, and I do see it when I search for "actual annual cooling".

Are you sure you're checking on staging (https://bedes-mapping-manager-staging.herokuapp.com)? Maybe quit your browser and try again? Are the "extra" composite terms you're seeing owned by you, or by someone else? Do you have another example besides "model" that I can test?

**Comment by robHitchcock** [comment] 2021-08-12 19:03
![image](https://user-images.githubusercontent.com/7998768/129253705-061a1ca9-a8f7-45ef-baf8-f8db443ad463.png)
[Model Search Results.docx](https://github.com/LBNL-ETA/BEDES-Manager/files/6977880/Model.Search.Results.docx)

**Comment by robHitchcock** [comment] 2021-08-12 19:07
I get the same results using Edge instead of Chrome
![image](https://user-images.githubusercontent.com/7998768/129254419-d88912db-8754-40a9-ab77-91ac217f925f.png)

**Comment by robHitchcock** [comment] 2021-08-12 19:10
Similar results when searching "project"
 
![image](https://user-images.githubusercontent.com/7998768/129254779-7b951a3a-d61a-4b7a-b6ef-0d5786910c90.png)

**Comment by robHitchcock** [comment] 2021-08-12 19:27
@TravisWalterLBNL I have created some Public Composite Terms: Heat Pump Model Number, Heat Pump Location, Project Identifier. Try searching for "Map To Existing Term" for some random text and see if these appear now in your results.

**Comment by TravisWalterLBNL** [comment] 2021-08-12 20:07
Very strange. I see all 3 of those composite terms when I search for "cooling" under "Map To Existing Term". Also, when I search for "model" now, I see the same results as before, but I also see those 3 composite terms. I still don't see "Actual Annual Cooling Degree Days Weather Metric Value" when I search for "model", but I do see it when I search for "cooling".

@wizonesolutions I think you'll have to take over from here. We are getting different search results from different accounts, and the results don't match the search criteria, and the results seem to be somehow dependent on whether the composite term was recently created.

**Comment by robHitchcock** [comment] 2021-08-12 20:17
Perhaps the search results are somehow including all Public Composite Terms for users other than yourself?

**Comment by wizonesolutions** [comment] 2021-08-25 15:27
@TravisWalterLBNL @robHitchcock Could y'all reassess this now that we've refreshed the data on staging, just so we can rule that out and narrow down what fix(es) is/are needed here?

**Comment by wizonesolutions** [comment] 2022-02-18 10:39
@TravisWalterLBNL Asked about this one in #203. I'll read the history and take a look myself today, so disregard that question. I will re-ask if I can't figure out what should be done from the existing conversation or have trouble reproducing the issues 👍

**Comment by TravisWalterLBNL** [comment] 2022-02-21 22:27
Looks good on staging. Will close after testing on production.

**Comment by wizonesolutions** [comment] 2022-02-23 16:43
Deployed to production.

**Comment by TravisWalterLBNL** [comment] 2022-02-23 20:20
Fixed on production.

**Closed by TravisWalterLBNL** 2022-02-23 20:20 UTC
Labels: bug, high priority
