### ISSUE TITLE
search results should exclude items with Sharing=Public be default

### ISSUE THREAD

**Issue by phgupta** [LBNL-ETA/BEDES-Manager#95] opened 2020-02-13 00:30 UTC
Default behavior should show private and BEDES approved terms only.

Need to come up with a way on how to show public terms as well. Two solutions so far,
1. Add a button on the UI that toggles to show public terms as well.
2. Sort the search results to show private and approved terms first and the public terms in the end.

**Comment by TravisWalterLBNL** [comment] 2021-05-13 20:24
There is already functionality that allows filtering results, so one solution would be to make the default be to filter the Sharing column on Sharing not equal Public. But, we would need a way to indicate to the user that this filter is there so that they can take it off if they want to see public terms.

**Comment by TravisWalterLBNL** [comment] 2021-05-13 20:27
I changed the title of this issue because this same behavior is needed not just when searcing for composite tems, but also when on the "Search for Terms" page (which searches both atomic and composite terms), and when on the "Applications" page.

**Comment by wizonesolutions** [comment] 2021-09-24 16:28
@TravisWalterLBNL We do have the filter, but as you say, we need a way to indicate it to the user. The filter is a text filter, as well, which isn't intuitive.

![image](https://user-images.githubusercontent.com/344116/134709093-074c4c9a-d90f-419f-9a44-cf9c4d46f4f5.png)

I'm going to add a checkbox to the right of the Search button that says, "Also show public terms" ("Also show public applications"). If the filters are modifiable in code, this will automatically add/remove a [Sharing] [Equals] ["Public"] filter. If not, I will handle it through the search API on the backend.

I figure this is a good starting point. We can refine it from there if necessary.

**Comment by wizonesolutions** [comment] 2021-09-24 16:31
Ah, actually, using that filter only reduces the result set, so I will have to do it through the API anyway. By default, it won't send Public terms in the result payload, but when the checkbox is checked, they will be included. The user will have to filter for them manually if they want.

**Comment by wizonesolutions** [comment] 2021-09-28 14:05
@TravisWalterLBNL @caseycobb  following up on this

**Comment by TravisWalterLBNL** [comment] 2021-09-28 17:16
I'm not sure I understand. Do you have a version I can experiment with? Or, do you need more information?

**Comment by wizonesolutions** [comment] 2021-09-29 09:23
I'll do this up as it is in my head and put it on staging. We can tweak the
visuals from there as necessary. That'll be easier. The backend work won't
be significantly different regardless.

**Comment by wizonesolutions** [comment] 2021-10-18 19:31
Question 3: Right now, anonymous visitors cannot search for applications. Should we restrict seeing Public applications to authenticated users as well, or should the checkbox be shown in both scenarios/

**Comment by wizonesolutions** [comment] 2021-11-01 15:48
> The "Show public terms" checkbox shouldn't be on the "Search for Terms" page. That page should only be searching BEDES atomic terms and list options, which are always public. Right now, it is showing composite terms in the results, so those need to be removed.

That's #203, which isn't done yet. However, I'll remove the frontend changes there, since we know it's coming.

**Comment by wizonesolutions** [comment] 2021-11-01 16:30
> Rob is the owner of a public composite term called "Project identifier". On the "Composite Terms" page, the "Show public terms" checkbox is working correctly: If I search for "project identifier" with the box unchecked, I see no results, and when I check the box, I see Rob's term. However, on the "Applications" page, if I make a new application term, then click "Map To existing BEDES Term", then search for "project identifier" with the "Show public terms" box checked, I do not see Rob's "Project identifier" in the results, but it should be there.

I cannot reproduce this: 
![image](https://user-images.githubusercontent.com/344116/139705936-c0ce5f1f-5896-4e90-9659-7587fbfcef86.png)

Both as an admin and as a regular user, I see Rob's term when the box is checked. Could you have missed it in the output, or not clicked the Search button again after checking the box? That dialog does not update as you type. We may want to open an issue to try and standardize the behavior there, honestly (either search on typing or don't), but things look to be working properly. Let me know if I am looking at the wrong screen. I clicked into an application and went to map a term to a new application term.

**Comment by wizonesolutions** [comment] 2021-11-01 16:31
> On the "Applications" page, with nothing entered in the search box, I am seeing a public application called "Rob test application 11" that is owned by Rob, even though the "Show public applications" box is not checked. Maybe it's because I am using an admin account?

Yes, that's the reason. As a regular user, I see:

![Uploading image.png…]()

**Comment by wizonesolutions** [comment] 2021-11-01 16:32
I've pushed the Search for Terms fix, and it's deploying. Check in 15 minutes or so.

**Comment by TravisWalterLBNL** [comment] 2021-11-01 17:31
> Both as an admin and as a regular user, I see Rob's term when the box is checked. Could you have missed it in the output, or not clicked the Search button again after checking the box? That dialog does not update as you type. We may want to open an issue to try and standardize the behavior there, honestly (either search on typing or don't), but things look to be working properly. Let me know if I am looking at the wrong screen. I clicked into an application and went to map a term to a new application term.

OK, I can see the term now. First, I typed the search string, then I clicked "Search", then I checked the "Show public terms" box, but I couldn't see the term. But, if I clicked "Search" again, the term showed up. Similarly, in order to make the term go away, I had to first uncheck "Show public terms", then click "Search". So, it looks like the "Show public terms" checkbox doesn't take any affect until "Search" is clicked. To me, this is counterintuitive. Can we make it so that the search results are updated automatically whenever the "Show public terms" checkbox is toggled (without needing to click "Search")?

I agree that we should standardize the behavior of all our search boxes so that the search results updated as you type (and as you toggle the "Show public terms" box). I will make a separate issue for this.

**Comment by TravisWalterLBNL** [comment] 2021-11-04 17:44
There's still something strange going on: When I first go to the site, then go to the "Composite Terms" page, the "Show public terms" box is unchecked and I don't see any public terms. This is correct. If I then check the "Show public terms" box, I see some public terms. Still correct. But, if I then go to the "Search for terms" page, then back to the "Composite Terms" page, the "Show public terms" box is unchecked, but I see some public terms. That shouldn't happen. If I refresh the page, the box stays uncheck and now the public terms are gone, as they should be. So, it seems like leaving the "Composite Terms" page then coming back to it resets the checkbox to its default (unchecked), but doesn't update the search results accordingly, causing the checkbox and the search results to be out of sync.

The "Applications" page has the same problem as the "Composite Terms" page.

**Comment by wizonesolutions** [comment] 2021-11-04 19:21
I think I know what's causing this. It's easier to fix it by having the checkbox keep its state and tying that to whether we're showing public terms or not. Is that an OK solution for you, or do you specifically want the state of everything to reset when leaving and coming back?

**Comment by TravisWalterLBNL** [comment] 2021-11-04 21:22
The easy fix sounds fine to me.

**Comment by wizonesolutions** [comment] 2021-11-08 18:42
This should be up on staging in about 15 minutes. This also includes the Angular 13.0 upgrade, so put the application through its paces and test things like importing a mapping CSV. I spot-tested login, search, etc. on my end, so I expect it will all still work.

**Comment by wizonesolutions** [comment] 2021-11-08 19:16
(Build broken; debugging.)

**Comment by wizonesolutions** [comment] 2021-11-08 21:02
It's back up.

**Comment by wizonesolutions** [comment] 2021-11-15 13:05
Have you had a chance to review this?

**Comment by wizonesolutions** [comment] 2021-11-15 13:06
@TravisWalterLBNL

**Comment by TravisWalterLBNL** [comment] 2021-11-15 17:33
OK, this looks good to me. @robHitchcock, have you had a chance to test this?

**Comment by robHitchcock** [comment] 2021-11-15 19:14
@TravisWalterLBNL @wizonesolutions I have tested the new search with Show public terms checkbox. Very nice, rapid dynamic display of search results. Show public terms checkbox seems to work well.
I also tested import of CSV for a new Application. The import worked with all new terms created in the Application Terms list. However, the new terms listed in the Application had Owner blank, and Sharing blank except for the one Composite Term that already existed from another Application mapping. Also, the newly imported Composite Terms do not show up in the Composite Terms tab.
If I log out and close the site, then log back in, the previously existing Composite Term now correctly shows me as Owner and Sharing as Public under the list of Application Terms, but the newly imported Composite Terms still have blank Owner and Sharing fields, and still do not show up on the Composite Terms tab, nor are they listed in an explicit search of Composite Terms.

**Comment by robHitchcock** [comment] 2021-11-17 22:42
@TravisWalterLBNL @wizonesolutions My mistake - the blank Owner and Sharing fields issue is covered in another issue because the blanks are for Atomic Terms, not Composite Terms.

**Comment by TravisWalterLBNL** [comment] 2021-11-17 22:44
@wizonesolutions OK, this looks good on staging. Let us know when it has been pushed to production and we'll test it there.

**Comment by wizonesolutions** [comment] 2021-11-22 11:46
@TravisWalterLBNL @robHitchcock This is on production now.

**Comment by TravisWalterLBNL** [comment] 2021-12-07 18:38
Looks good on production. Closing this issue.

**Closed** 2021-12-07 18:37 UTC
Labels: bug, high priority
