### ISSUE TITLE
Warn user of duplicates when creating new composite term

### ISSUE THREAD

**Issue by phgupta** [LBNL-ETA/BEDES-Manager#94] opened 2020-02-13 00:26 UTC
Check if existing BEDES approved composite term exists and give an alert to the user.

**Comment by TravisWalterLBNL** [comment] 2020-02-19 22:17
When checking for duplicates, should check the individual atomic terms, rather than the concatenated composite term name (to avoid issues with non-unique concatenated names).

**Comment by TravisWalterLBNL** [comment] 2020-02-19 22:18
Also, maybe warn a user if there is another composite term that has different atomic terms but the same concatenated name.

**Comment by TravisWalterLBNL** [comment] 2021-02-10 22:40
An alert should be given when the user is trying to create a composite term manually from the "Composite Terms" section of the site.

If the user is importing an application, and an app term is mapped to a composite term that already exists as a BEDES approved term, then the behavior should be this: if the UUID of the composite term is specified in the import file and is different than the UUID of the BEDES approved term, then the user's copy of the composite term should be created and the app term should be mapped to it. Otherwise, it should be mapped to the BEDES approved term.

**Comment by wizonesolutions** [comment] 2021-04-23 10:32
@TravisWalterLBNL @robHitchcock I am wondering if we should split up this issue to make things simpler. I can see three things we want to do here:

1) More robust duplicate checking. It would be good to specify some concrete examples here so that I can ensure the behavior matches. By concrete examples I mean something like:

```
Given I am a regular user
And I'm creating a composite term
And I select the atomic term "One"
And I select the atomic term "Two"
And a composite term named "One Two" already exists in the system
And the existing composite term named "One Two" contains the atomic terms "One" and "Two"
When I click "Save"
Then I should see "A conflicting composite term already exists: One Two"
```

(This is called BDD, but it's not important to follow the format precisely. It's just a decent way to specify testing scenarios.)

2) Warning the user about the same concatenated name being used with different terms. (At what stage should the warning happen? Before save as soon as the terms are selected?) Concrete examples would be good here.

3) Matching terms on import if the UUIDs are the same (I assume that the user's copy of the composite term is already created by default).

**Comment by robHitchcock** [comment] 2021-04-27 23:09
@wizonesolutions Yes we can split this issue up as you indicate. 

Here is an example of your #1 duplicate composite term creation:
- Given I am a regular user
- I am manually creating a composite term "Baseline Measure Description" on the Composite Terms tab
- I select the atomic term "Baseline" from the "Temporal Status" constrained list
- I select the atomic term "Measure" from the "Action Category" constrained list
- I select the atomic term "Description" to hold a text value
- A BEDES approved composite term named "Baseline Measure Description" already exists using the same atomic terms
- When I click on "Save"
- Then I should see the warning "A duplicate composite term already exists using these atomic terms"
- Then the system should return to the Composite Terms list without saving the duplicate composite term

Here is an example of your #2 concatenated name being used with different atomic terms:
- Given I am a regular user
- I am manually creating a composite term "Above Grade Floor Quantity" on the Composite Terms tab
- I select the atomic term "Above grade" from the "Location" constrained list
- I select the atomic term "Floor" from the "Opaque Surface" constrained list
- I select the atomic term "Quantity" to hold an integer count value
- A BEDES approved composite term named "Above Grade Floor Quantity" already exists, but contains the atomic term "Floor" from the "Spatial Unit Type" constrained list rather than from the "Opaque Surface" constrained list
- When I click on "Save"
- Then I should see the warning "A conflicting composite term already exists using different atomic terms: 'Above grade' (List: Location), 'Floor' (List: Spatial Unit Type), 'Quantity'"
- // if the detail of the different atomic terms is too difficult to include in the warning message then just the text prior to the ":" is acceptable //
- Then the system should offer the option of saving this conflicting composite term or not as a Private composite term

I am not sure I agree with Travis' action scenario for the importing and auto-creation of conflicting composite terms. We will have to wait until his return to reconcile that scenario.

**Comment by wizonesolutions** [comment] 2021-04-30 11:36
Thanks @robHitchcock. This is clear. I think we can keep this as one issue, but I'll update the title to better capture what it is.

**Comment by wizonesolutions** [comment] 2021-04-30 12:35
@robHitchcock Actually, just to address Travis's point in https://github.com/LBNL-ETA/BEDES-Manager/issues/94#issuecomment-588501042: in scenario 1, if they try to create "Description Baseline Measure", do we allow that? I am not 100% sure what he meant by checking the individual atomic terms rather than the concatenated name. Your spec seems to say that we should check the concatenated name.

Basically: Does atomic term order matter when checking for duplicate composite terms?

I'm going to proceed assuming that we only care about concatenated names for now.

**Comment by robHitchcock** [comment] 2021-04-30 17:26
@wizonesolutions The intent is to check atomic terms. The checking of individual atomic terms would use the UUID of the atomic term rather than the text of the term. That is the basis of the 2nd example where there are two ways to get to "Above Grade Floor Quantity"

Interesting question about order. I believe that order should matter. We should think more about that when Travis returns next week. We have discussed this before, but I'm not sure where we stand at the moment.

**Comment by wizonesolutions** [comment] 2021-04-30 17:47
@robHitchcock Thanks—yeah, for the first one, I will check atomic terms by UUID, since that's the only way to determine if it's a true duplicate. For the second one, those will be checked in the sense that they won't cause the first scenario but might cause the second scenario afterward, if that makes sense. But validation-wise, I have to check the text of the term for the second one (since at that point we will know the UUIDs don't match).

I'll make order matter, and we can adjust that later if needed.

**Comment by robHitchcock** [comment] 2021-04-30 17:53
@wizonesolutions Sounds good

**Comment by TravisWalterLBNL** [comment] 2021-05-05 22:47
Also, I have a case where I am importing an application mapping that has two different application terms that are both mapped to the same composite term (the UUID is not specified in the import file). The current behavior is that two copies of the composite term are created, each with a different UUID, and each application term is mapped to a different composite term. I think the desired behavior would be for only one copy of the composite term to be created, and for both application terms to be mapped to the same composite term. Only if the import file specifies UUIDs for the composite terms (and the specified UUIDs are different) should two copies of the composite term get created on import.

**Comment by TravisWalterLBNL** [comment] 2021-05-11 17:13
Duplicate checking rules upon import don't need to be the same rules as when creating composite terms manually in the app. In the app, you shouldn't be allowed to create a duplicate of an approved composite term. Upon import, you should be allowed to, but only if you go through the trouble of specifying a UUID for the composite term, and that UUID is different than the UUID of the approved composite term. If you don't specify the UUID for the composite term upon import, the application term should be automatically mapped to the approved copy of the composite term.

**Comment by robHitchcock** [comment] 2021-05-12 18:45
I don't understand the need, nor the wisdom, of allowing duplicate composite terms with conflicting UUIDs. In my mind, it can lead to confusion down the road when/if a user makes the duplicate composite term Public, and then other users include it in their mappings that will be used as the basis for data transformations. Why would a user need a duplicate composite term with different UUID?
I also don't think it wise to implement different checking rules in different processes with the Mapping Manager.

**Comment by TravisWalterLBNL** [comment] 2021-05-12 20:15
One reason for allowing multiple copies of the same composite term is units. Maybe one user wants the copy of Gross Floor Area that uses ft^2 and another wants m^2. If we only have one copy of the composite term with ft^2, then the user that has m^2 in their application will have to map their application term to a composite term with a different unit.

**Comment by TravisWalterLBNL** [comment] 2021-05-12 20:19
I understand not allowing a user to create a composite term that already exists as an approved composite term. However, what should happen if one user creates a composite term and keeps it private, then another user creates that same composite term and wants theirs to be private too? Is there still only one copy? If so, who owns it? Does one user have an application term mapped to a composite term that is owned by another user and is private? What if the owner wants to delete it, but the other user doesn't? Does ownership transfer?

**Comment by robHitchcock** [comment] 2021-05-12 20:36
I think the duplicate composite terms with differing units may actually be an argument against, rather than for. Isn't that how NASA missed Mars?
The complications of duplicate unshared Private terms is a good point. Does import currently check incoming composite terms against all Approved/Public/Private terms indiscriminately? If so, we may need to enhance that checking to allow duplicate Private terms, warn of duplication of Public terms, and disallow duplication of Approved terms.

**Comment by TravisWalterLBNL** [comment] 2021-05-13 21:31
@wizonesolutions Take a break on this issue until we've had a chance to work it out internally.

**Comment by TravisWalterLBNL** [comment] 2021-05-20 17:13
Closing this issue for clarity. I will create new more specific issues as necessary.

**Closed by TravisWalterLBNL** 2021-05-20 17:13 UTC
Labels: bug, high priority
